<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE HolyQuran [
	<!ATTLIST HolyQuran TranslationID CDATA #REQUIRED>
	<!ATTLIST HolyQuran Writer CDATA #REQUIRED>
	<!ATTLIST HolyQuran Language CDATA #REQUIRED>
	<!ATTLIST HolyQuran LanguageIsoCode CDATA #REQUIRED>
	<!ATTLIST HolyQuran Direction (rtl|ltr) #REQUIRED>
	<!ELEMENT HolyQuran (Chapter+)>
	<!ATTLIST Chapter ChapterID CDATA #REQUIRED>
	<!ATTLIST Chapter ChapterName CDATA #REQUIRED>
	<!ELEMENT Chapter (Verse+)>
	<!ATTLIST Verse VerseID CDATA #REQUIRED>
	<!ELEMENT Verse (#PCDATA)>
]>
<!-- This SQL Query Generated at 31 July 2014 11:06 (UTC) from www.qurandatabase.org -->
<HolyQuran TranslationID="59" Writer="Yusuf Ali" Language="English" LanguageIsoCode="eng" Direction="ltr">
	<Chapter ChapterID="1" ChapterName="The Opening">
		<Verse VerseID="1"><![CDATA[In the name of Allah, Most Gracious, Most Merciful.]]></Verse>
		<Verse VerseID="2"><![CDATA[Praise be to Allah, the Cherisher and Sustainer of the worlds;]]></Verse>
		<Verse VerseID="3"><![CDATA[Most Gracious, Most Merciful;]]></Verse>
		<Verse VerseID="4"><![CDATA[Master of the Day of Judgment.]]></Verse>
		<Verse VerseID="5"><![CDATA[Thee do we worship, and Thine aid we seek.]]></Verse>
		<Verse VerseID="6"><![CDATA[Show us the straight way,]]></Verse>
		<Verse VerseID="7"><![CDATA[The way of those on whom Thou hast bestowed Thy Grace, those whose (portion) is not wrath, and who go not astray.]]></Verse>
	</Chapter>
	<Chapter ChapterID="2" ChapterName="The Cow">
		<Verse VerseID="1"><![CDATA[A.L.M.]]></Verse>
		<Verse VerseID="2"><![CDATA[This is the Book; in it is guidance sure, without doubt, to those who fear Allah;]]></Verse>
		<Verse VerseID="3"><![CDATA[Who believe in the Unseen, are steadfast in prayer, and spend out of what We have provided for them;]]></Verse>
		<Verse VerseID="4"><![CDATA[And who believe in the Revelation sent to thee, and sent before thy time, and (in their hearts) have the assurance of the Hereafter.]]></Verse>
		<Verse VerseID="5"><![CDATA[They are on (true) guidance, from their Lord, and it is these who will prosper.]]></Verse>
		<Verse VerseID="6"><![CDATA[As to those who reject Faith, it is the same to them whether thou warn them or do not warn them; they will not believe.]]></Verse>
		<Verse VerseID="7"><![CDATA[Allah hath set a seal on their hearts and on their hearing, and on their eyes is a veil; great is the penalty they (incur).]]></Verse>
		<Verse VerseID="8"><![CDATA[Of the people there are some who say: "We believe in Allah and the Last Day;" but they do not (really) believe.]]></Verse>
		<Verse VerseID="9"><![CDATA[Fain would they deceive Allah and those who believe, but they only deceive themselves, and realise (it) not!]]></Verse>
		<Verse VerseID="10"><![CDATA[In their hearts is a disease; and Allah has increased their disease: And grievous is the penalty they (incur), because they are false (to themselves).]]></Verse>
		<Verse VerseID="11"><![CDATA[When it is said to them: "Make not mischief on the earth," they say: "Why, we only Want to make peace!"]]></Verse>
		<Verse VerseID="12"><![CDATA[Of a surety, they are the ones who make mischief, but they realise (it) not.]]></Verse>
		<Verse VerseID="13"><![CDATA[When it is said to them: "Believe as the others believe:" They say: "Shall we believe as the fools believe?" Nay, of a surety they are the fools, but they do not know.]]></Verse>
		<Verse VerseID="14"><![CDATA[When they meet those who believe, they say: "We believe;" but when they are alone with their evil ones, they say: "We are really with you: We (were) only jesting."]]></Verse>
		<Verse VerseID="15"><![CDATA[Allah will throw back their mockery on them, and give them rope in their trespasses; so they will wander like blind ones (To and fro).]]></Verse>
		<Verse VerseID="16"><![CDATA[These are they who have bartered Guidance for error: But their traffic is profitless, and they have lost true direction,]]></Verse>
		<Verse VerseID="17"><![CDATA[Their similitude is that of a man who kindled a fire; when it lighted all around him, Allah took away their light and left them in utter darkness. So they could not see.]]></Verse>
		<Verse VerseID="18"><![CDATA[Deaf, dumb, and blind, they will not return (to the path).]]></Verse>
		<Verse VerseID="19"><![CDATA[Or (another similitude) is that of a rain-laden cloud from the sky: In it are zones of darkness, and thunder and lightning: They press their fingers in their ears to keep out the stunning thunder-clap, the while they are in terror of death. But Allah is ever round the rejecters of Faith!]]></Verse>
		<Verse VerseID="20"><![CDATA[The lightning all but snatches away their sight; every time the light (Helps) them, they walk therein, and when the darkness grows on them, they stand still. And if Allah willed, He could take away their faculty of hearing and seeing; for Allah hath power over all things.]]></Verse>
		<Verse VerseID="21"><![CDATA[O ye people! Adore your Guardian-Lord, who created you and those who came before you, that ye may have the chance to learn righteousness;]]></Verse>
		<Verse VerseID="22"><![CDATA[Who has made the earth your couch, and the heavens your canopy; and sent down rain from the heavens; and brought forth therewith Fruits for your sustenance; then set not up rivals unto Allah when ye know (the truth).]]></Verse>
		<Verse VerseID="23"><![CDATA[And if ye are in doubt as to what We have revealed from time to time to Our servant, then produce a Sura like thereunto; and call your witnesses or helpers (If there are any) besides Allah, if your (doubts) are true.]]></Verse>
		<Verse VerseID="24"><![CDATA[But if ye cannot- and of a surety ye cannot- then fear the Fire whose fuel is men and stones,- which is prepared for those who reject Faith.]]></Verse>
		<Verse VerseID="25"><![CDATA[But give glad tidings to those who believe and work righteousness, that their portion is Gardens, beneath which rivers flow. Every time they are fed with fruits therefrom, they say: "Why, this is what we were fed with before," for they are given things in similitude; and they have therein companions pure (and holy); and they abide therein (for ever).]]></Verse>
		<Verse VerseID="26"><![CDATA[Allah disdains not to use the similitude of things, lowest as well as highest. Those who believe know that it is truth from their Lord; but those who reject Faith say: "What means Allah by this similitude?" By it He causes many to stray, and many He leads into the right path; but He causes not to stray, except those who forsake (the path),-]]></Verse>
		<Verse VerseID="27"><![CDATA[Those who break Allah´s Covenant after it is ratified, and who sunder what Allah Has ordered to be joined, and do mischief on earth: These cause loss (only) to themselves.]]></Verse>
		<Verse VerseID="28"><![CDATA[How can ye reject the faith in Allah?- seeing that ye were without life, and He gave you life; then will He cause you to die, and will again bring you to life; and again to Him will ye return.]]></Verse>
		<Verse VerseID="29"><![CDATA[It is He Who hath created for you all things that are on earth; Moreover His design comprehended the heavens, for He gave order and perfection to the seven firmaments; and of all things He hath perfect knowledge.]]></Verse>
		<Verse VerseID="30"><![CDATA[Behold, thy Lord said to the angels: "I will create a vicegerent on earth." They said: "Wilt Thou place therein one who will make mischief therein and shed blood?- whilst we do celebrate Thy praises and glorify Thy holy (name)?" He said: "I know what ye know not."]]></Verse>
		<Verse VerseID="31"><![CDATA[And He taught Adam the names of all things; then He placed them before the angels, and said: "Tell me the names of these if ye are right."]]></Verse>
		<Verse VerseID="32"><![CDATA[They said: "Glory to Thee, of knowledge We have none, save what Thou Hast taught us: In truth it is Thou Who art perfect in knowledge and wisdom."]]></Verse>
		<Verse VerseID="33"><![CDATA[He said: "O Adam! Tell them their names." When he had told them, Allah said: "Did I not tell you that I know the secrets of heaven and earth, and I know what ye reveal and what ye conceal?"]]></Verse>
		<Verse VerseID="34"><![CDATA[And behold, We said to the angels: "Bow down to Adam" and they bowed down. Not so Iblis: he refused and was haughty: He was of those who reject Faith.]]></Verse>
		<Verse VerseID="35"><![CDATA[We said: "O Adam! dwell thou and thy wife in the Garden; and eat of the bountiful things therein as (where and when) ye will; but approach not this tree, or ye run into harm and transgression."]]></Verse>
		<Verse VerseID="36"><![CDATA[Then did Satan make them slip from the (garden), and get them out of the state (of felicity) in which they had been. We said: "Get ye down, all (ye people), with enmity between yourselves. On earth will be your dwelling-place and your means of livelihood - for a time."]]></Verse>
		<Verse VerseID="37"><![CDATA[Then learnt Adam from his Lord words of inspiration, and his Lord Turned towards him; for He is Oft-Returning, Most Merciful.]]></Verse>
		<Verse VerseID="38"><![CDATA[We said: "Get ye down all from here; and if, as is sure, there comes to you Guidance from me, whosoever follows My guidance, on them shall be no fear, nor shall they grieve.]]></Verse>
		<Verse VerseID="39"><![CDATA["But those who reject Faith and belie Our Signs, they shall be companions of the Fire; they shall abide therein."]]></Verse>
		<Verse VerseID="40"><![CDATA[O Children of Israel! call to mind the (special) favour which I bestowed upon you, and fulfil your covenant with Me as I fulfil My Covenant with you, and fear none but Me.]]></Verse>
		<Verse VerseID="41"><![CDATA[And believe in what I reveal, confirming the revelation which is with you, and be not the first to reject Faith therein, nor sell My Signs for a small price; and fear Me, and Me alone.]]></Verse>
		<Verse VerseID="42"><![CDATA[And cover not Truth with falsehood, nor conceal the Truth when ye know (what it is).]]></Verse>
		<Verse VerseID="43"><![CDATA[And be steadfast in prayer; practise regular charity; and bow down your heads with those who bow down (in worship).]]></Verse>
		<Verse VerseID="44"><![CDATA[Do ye enjoin right conduct on the people, and forget (To practise it) yourselves, and yet ye study the Scripture? Will ye not understand?]]></Verse>
		<Verse VerseID="45"><![CDATA[Nay, seek (Allah´s) help with patient perseverance and prayer: It is indeed hard, except to those who bring a lowly spirit,-]]></Verse>
		<Verse VerseID="46"><![CDATA[Who bear in mind the certainty that they are to meet their Lord, and that they are to return to Him.]]></Verse>
		<Verse VerseID="47"><![CDATA[Children of Israel! call to mind the (special) favour which I bestowed upon you, and that I preferred you to all other (for My Message).]]></Verse>
		<Verse VerseID="48"><![CDATA[Then guard yourselves against a day when one soul shall not avail another nor shall intercession be accepted for her, nor shall compensation be taken from her, nor shall anyone be helped (from outside).]]></Verse>
		<Verse VerseID="49"><![CDATA[And remember, We delivered you from the people of Pharaoh: They set you hard tasks and punishments, slaughtered your sons and let your women-folk live; therein was a tremendous trial from your Lord.]]></Verse>
		<Verse VerseID="50"><![CDATA[And remember We divided the sea for you and saved you and drowned Pharaoh´s people within your very sight.]]></Verse>
		<Verse VerseID="51"><![CDATA[And remember We appointed forty nights for Moses, and in his absence ye took the calf (for worship), and ye did grievous wrong.]]></Verse>
		<Verse VerseID="52"><![CDATA[Even then We did forgive you; there was a chance for you to be grateful.]]></Verse>
		<Verse VerseID="53"><![CDATA[And remember We gave Moses the Scripture and the Criterion (Between right and wrong): There was a chance for you to be guided aright.]]></Verse>
		<Verse VerseID="54"><![CDATA[And remember Moses said to his people: "O my people! Ye have indeed wronged yourselves by your worship of the calf: So turn (in repentance) to your Maker, and slay yourselves (the wrong-doers); that will be better for you in the sight of your Maker." Then He turned towards you (in forgiveness): For He is Oft-Returning, Most Merciful.]]></Verse>
		<Verse VerseID="55"><![CDATA[And remember ye said: "O Moses! We shall never believe in thee until we see Allah manifestly," but ye were dazed with thunder and lighting even as ye looked on.]]></Verse>
		<Verse VerseID="56"><![CDATA[Then We raised you up after your death: Ye had the chance to be grateful.]]></Verse>
		<Verse VerseID="57"><![CDATA[And We gave you the shade of clouds and sent down to you Manna and quails, saying: "Eat of the good things We have provided for you:" (But they rebelled); to us they did no harm, but they harmed their own souls.]]></Verse>
		<Verse VerseID="58"><![CDATA[And remember We said: "Enter this town, and eat of the plenty therein as ye wish; but enter the gate with humility, in posture and in words, and We shall forgive you your faults and increase (the portion of) those who do good."]]></Verse>
		<Verse VerseID="59"><![CDATA[But the transgressors changed the word from that which had been given them; so We sent on the transgressors a plague from heaven, for that they infringed (Our command) repeatedly.]]></Verse>
		<Verse VerseID="60"><![CDATA[And remember Moses prayed for water for his people; We said: "Strike the rock with thy staff." Then gushed forth therefrom twelve springs. Each group knew its own place for water. So eat and drink of the sustenance provided by Allah, and do no evil nor mischief on the (face of the) earth.]]></Verse>
		<Verse VerseID="61"><![CDATA[And remember ye said: "O Moses! we cannot endure one kind of food (always); so beseech thy Lord for us to produce for us of what the earth groweth, -its pot-herbs, and cucumbers, Its garlic, lentils, and onions." He said: "Will ye exchange the better for the worse? Go ye down to any town, and ye shall find what ye want!" They were covered with humiliation and misery; they drew on themselves the wrath of Allah. This because they went on rejecting the Signs of Allah and slaying His Messengers without just cause. This because they rebelled and went on transgressing.]]></Verse>
		<Verse VerseID="62"><![CDATA[Those who believe (in the Qur´an), and those who follow the Jewish (scriptures), and the Christians and the Sabians,- any who believe in Allah and the Last Day, and work righteousness, shall have their reward with their Lord; on them shall be no fear, nor shall they grieve.]]></Verse>
		<Verse VerseID="63"><![CDATA[And remember We took your covenant and We raised above you (The towering height) of Mount (Sinai) : (Saying): "Hold firmly to what We have given you and bring (ever) to remembrance what is therein: Perchance ye may fear Allah."]]></Verse>
		<Verse VerseID="64"><![CDATA[But ye turned back thereafter: Had it not been for the Grace and Mercy of Allah to you, ye had surely been among the lost.]]></Verse>
		<Verse VerseID="65"><![CDATA[And well ye knew those amongst you who transgressed in the matter of the Sabbath: We said to them: "Be ye apes, despised and rejected."]]></Verse>
		<Verse VerseID="66"><![CDATA[So We made it an example to their own time and to their posterity, and a lesson to those who fear Allah.]]></Verse>
		<Verse VerseID="67"><![CDATA[And remember Moses said to his people: "Allah commands that ye sacrifice a heifer." They said: "Makest thou a laughing-stock of us?" He said: "Allah save me from being an ignorant (fool)!"]]></Verse>
		<Verse VerseID="68"><![CDATA[They said: "Beseech on our behalf Thy Lord to make plain to us what (heifer) it is!" He said; "He says: The heifer should be neither too old nor too young, but of middling age. Now do what ye are commanded!"]]></Verse>
		<Verse VerseID="69"><![CDATA[They said: "Beseech on our behalf Thy Lord to make plain to us Her colour." He said: "He says: A fawn-coloured heifer, pure and rich in tone, the admiration of beholders!"]]></Verse>
		<Verse VerseID="70"><![CDATA[They said: "Beseech on our behalf Thy Lord to make plain to us what she is: To us are all heifers alike: We wish indeed for guidance, if Allah wills."]]></Verse>
		<Verse VerseID="71"><![CDATA[He said: "He says: A heifer not trained to till the soil or water the fields; sound and without blemish." They said: "Now hast thou brought the truth." Then they offered her in sacrifice, but not with good-will.]]></Verse>
		<Verse VerseID="72"><![CDATA[Remember ye slew a man and fell into a dispute among yourselves as to the crime: But Allah was to bring forth what ye did hide.]]></Verse>
		<Verse VerseID="73"><![CDATA[So We said: "Strike the (body) with a piece of the (heifer)." Thus Allah bringeth the dead to life and showeth you His Signs: Perchance ye may understand.]]></Verse>
		<Verse VerseID="74"><![CDATA[Thenceforth were your hearts hardened: They became like a rock and even worse in hardness. For among rocks there are some from which rivers gush forth; others there are which when split asunder send forth water; and others which sink for fear of Allah. And Allah is not unmindful of what ye do.]]></Verse>
		<Verse VerseID="75"><![CDATA[Can ye (o ye men of Faith) entertain the hope that they will believe in you?- Seeing that a party of them heard the Word of Allah, and perverted it knowingly after they understood it.]]></Verse>
		<Verse VerseID="76"><![CDATA[Behold! when they meet the men of Faith, they say: "We believe": But when they meet each other in private, they say: "Shall you tell them what Allah hath revealed to you, that they may engage you in argument about it before your Lord?"- Do ye not understand (their aim)?]]></Verse>
		<Verse VerseID="77"><![CDATA[Know they not that Allah knoweth what they conceal and what they reveal?]]></Verse>
		<Verse VerseID="78"><![CDATA[And there are among them illiterates, who know not the Book, but (see therein their own) desires, and they do nothing but conjecture.]]></Verse>
		<Verse VerseID="79"><![CDATA[Then woe to those who write the Book with their own hands, and then say:"This is from Allah," to traffic with it for miserable price!- Woe to them for what their hands do write, and for the gain they make thereby.]]></Verse>
		<Verse VerseID="80"><![CDATA[And they say: "The Fire shall not touch us but for a few numbered days:" Say: "Have ye taken a promise from Allah, for He never breaks His promise? or is it that ye say of Allah what ye do not know?"]]></Verse>
		<Verse VerseID="81"><![CDATA[Nay, those who seek gain in evil, and are girt round by their sins,- they are companions of the Fire: Therein shall they abide (For ever).]]></Verse>
		<Verse VerseID="82"><![CDATA[But those who have faith and work righteousness, they are companions of the Garden: Therein shall they abide (For ever).]]></Verse>
		<Verse VerseID="83"><![CDATA[And remember We took a covenant from the Children of Israel (to this effect): Worship none but Allah; treat with kindness your parents and kindred, and orphans and those in need; speak fair to the people; be steadfast in prayer; and practise regular charity. Then did ye turn back, except a few among you, and ye backslide (even now).]]></Verse>
		<Verse VerseID="84"><![CDATA[And remember We took your covenant (to this effect): Shed no blood amongst you, nor turn out your own people from your homes: and this ye solemnly ratified, and to this ye can bear witness.]]></Verse>
		<Verse VerseID="85"><![CDATA[After this it is ye, the same people, who slay among yourselves, and banish a party of you from their homes; assist (Their enemies) against them, in guilt and rancour; and if they come to you as captives, ye ransom them, though it was not lawful for you to banish them. Then is it only a part of the Book that ye believe in, and do ye reject the rest? but what is the reward for those among you who behave like this but disgrace in this life?- and on the Day of Judgment they shall be consigned to the most grievous penalty. For Allah is not unmindful of what ye do.]]></Verse>
		<Verse VerseID="86"><![CDATA[These are the people who buy the life of this world at the price of the Hereafter: their penalty shall not be lightened nor shall they be helped.]]></Verse>
		<Verse VerseID="87"><![CDATA[We gave Moses the Book and followed him up with a succession of messengers; We gave Jesus the son of Mary Clear (Signs) and strengthened him with the holy spirit. Is it that whenever there comes to you a messenger with what ye yourselves desire not, ye are puffed up with pride?- Some ye called impostors, and others ye slay!]]></Verse>
		<Verse VerseID="88"><![CDATA[They say, "Our hearts are the wrappings (which preserve Allah´s Word: we need no more)." Nay, Allah´s curse is on them for their blasphemy: Little is it they believe.]]></Verse>
		<Verse VerseID="89"><![CDATA[And when there comes to them a Book from Allah, confirming what is with them,- although from of old they had prayed for victory against those without Faith,- when there comes to them that which they (should) have recognised, they refuse to believe in it but the curse of Allah is on those without Faith.]]></Verse>
		<Verse VerseID="90"><![CDATA[Miserable is the price for which they have sold their souls, in that they deny (the revelation) which Allah has sent down, in insolent envy that Allah of His Grace should send it to any of His servants He pleases: Thus have they drawn on themselves Wrath upon Wrath. And humiliating is the punishment of those who reject Faith.]]></Verse>
		<Verse VerseID="91"><![CDATA[When it is said to them, "Believe in what Allah Hath sent down, "they say, "We believe in what was sent down to us:" yet they reject all besides, even if it be Truth confirming what is with them. Say: "Why then have ye slain the prophets of Allah in times gone by, if ye did indeed believe?"]]></Verse>
		<Verse VerseID="92"><![CDATA[There came to you Moses with clear (Signs); yet ye worshipped the calf (Even) after that, and ye did behave wrongfully.]]></Verse>
		<Verse VerseID="93"><![CDATA[And remember We took your covenant and We raised above you (the towering height) of Mount (Sinai): (Saying): "Hold firmly to what We have given you, and hearken (to the Law)": They said:" We hear, and we disobey:" And they had to drink into their hearts (of the taint) of the calf because of their Faithlessness. Say: "Vile indeed are the behests of your Faith if ye have any faith!"]]></Verse>
		<Verse VerseID="94"><![CDATA[Say: "If the last Home, with Allah, be for you specially, and not for anyone else, then seek ye for death, if ye are sincere."]]></Verse>
		<Verse VerseID="95"><![CDATA[But they will never seek for death, on account of the (sins) which their hands have sent on before them. and Allah is well-acquainted with the wrong-doers.]]></Verse>
		<Verse VerseID="96"><![CDATA[Thou wilt indeed find them, of all people, most greedy of life,-even more than the idolaters: Each one of them wishes He could be given a life of a thousand years: But the grant of such life will not save him from (due) punishment. For Allah sees well all that they do.]]></Verse>
		<Verse VerseID="97"><![CDATA[Say: Whoever is an enemy to Gabriel-for he brings down the (revelation) to thy heart by Allah´s will, a confirmation of what went before, and guidance and glad tidings for those who believe,-]]></Verse>
		<Verse VerseID="98"><![CDATA[Whoever is an enemy to Allah and His angels and messengers, to Gabriel and Michael,- Lo! Allah is an enemy to those who reject Faith.]]></Verse>
		<Verse VerseID="99"><![CDATA[We have sent down to thee Manifest Signs (ayat); and none reject them but those who are perverse.]]></Verse>
		<Verse VerseID="100"><![CDATA[Is it not (the case) that every time they make a covenant, some party among them throw it aside?- Nay, Most of them are faithless.]]></Verse>
		<Verse VerseID="101"><![CDATA[And when there came to them a messenger from Allah, confirming what was with them, a party of the people of the Book threw away the Book of Allah behind their backs, as if (it had been something) they did not know!]]></Verse>
		<Verse VerseID="102"><![CDATA[They followed what the evil ones gave out (falsely) against the power of Solomon: the blasphemers Were, not Solomon, but the evil ones, teaching men Magic, and such things as came down at babylon to the angels Harut and Marut. But neither of these taught anyone (Such things) without saying: "We are only for trial; so do not blaspheme." They learned from them the means to sow discord between man and wife. But they could not thus harm anyone except by Allah´s permission. And they learned what harmed them, not what profited them. And they knew that the buyers of (magic) would have no share in the happiness of the Hereafter. And vile was the price for which they did sell their souls, if they but knew!]]></Verse>
		<Verse VerseID="103"><![CDATA[If they had kept their Faith and guarded themselves from evil, far better had been the reward from their Lord, if they but knew!]]></Verse>
		<Verse VerseID="104"><![CDATA[O ye of Faith! Say not (to the Messenger) words of ambiguous import, but words of respect; and hearken (to him): To those without Faith is a grievous punishment.]]></Verse>
		<Verse VerseID="105"><![CDATA[It is never the wish of those without Faith among the People of the Book, nor of the Pagans, that anything good should come down to you from your Lord. But Allah will choose for His special Mercy whom He will - for Allah is Lord of grace abounding.]]></Verse>
		<Verse VerseID="106"><![CDATA[None of Our revelations do We abrogate or cause to be forgotten, but We substitute something better or similar: Knowest thou not that Allah Hath power over all things?]]></Verse>
		<Verse VerseID="107"><![CDATA[Knowest thou not that to Allah belongeth the dominion of the heavens and the earth? And besides Him ye have neither patron nor helper.]]></Verse>
		<Verse VerseID="108"><![CDATA[Would ye question your Messenger as Moses was questioned of old? but whoever changeth from Faith to Unbelief, Hath strayed without doubt from the even way.]]></Verse>
		<Verse VerseID="109"><![CDATA[Quite a number of the People of the Book wish they could Turn you (people) back to infidelity after ye have believed, from selfish envy, after the Truth hath become Manifest unto them: But forgive and overlook, Till Allah accomplish His purpose; for Allah Hath power over all things.]]></Verse>
		<Verse VerseID="110"><![CDATA[And be steadfast in prayer and regular in charity: And whatever good ye send forth for your souls before you, ye shall find it with Allah: for Allah sees Well all that ye do.]]></Verse>
		<Verse VerseID="111"><![CDATA[And they say: "None shall enter Paradise unless he be a Jew or a Christian." Those are their (vain) desires. Say: "Produce your proof if ye are truthful."]]></Verse>
		<Verse VerseID="112"><![CDATA[Nay,-whoever submits His whole self to Allah and is a doer of good,- He will get his reward with his Lord; on such shall be no fear, nor shall they grieve.]]></Verse>
		<Verse VerseID="113"><![CDATA[The Jews say: "The Christians have naught (to stand) upon; and the Christians say: "The Jews have naught (To stand) upon." Yet they (Profess to) study the (same) Book. Like unto their word is what those say who know not; but Allah will judge between them in their quarrel on the Day of Judgment.]]></Verse>
		<Verse VerseID="114"><![CDATA[And who is more unjust than he who forbids that in places for the worship of Allah, Allah´s name should be celebrated?-whose zeal is (in fact) to ruin them? It was not fitting that such should themselves enter them except in fear. For them there is nothing but disgrace in this world, and in the world to come, an exceeding torment.]]></Verse>
		<Verse VerseID="115"><![CDATA[To Allah belong the east and the West: Whithersoever ye turn, there is the presence of Allah. For Allah is all-Pervading, all-Knowing.]]></Verse>
		<Verse VerseID="116"><![CDATA[They say: "Allah hath begotten a son" :Glory be to Him.-Nay, to Him belongs all that is in the heavens and on earth: everything renders worship to Him.]]></Verse>
		<Verse VerseID="117"><![CDATA[To Him is due the primal origin of the heavens and the earth: When He decreeth a matter, He saith to it: "Be," and it is.]]></Verse>
		<Verse VerseID="118"><![CDATA[Say those without knowledge: "Why speaketh not Allah unto us? or why cometh not unto us a Sign?" So said the people before them words of similar import. Their hearts are alike. We have indeed made clear the Signs unto any people who hold firmly to Faith (in their hearts).]]></Verse>
		<Verse VerseID="119"><![CDATA[Verily We have sent thee in truth as a bearer of glad tidings and a warner: But of thee no question shall be asked of the Companions of the Blazing Fire.]]></Verse>
		<Verse VerseID="120"><![CDATA[Never will the Jews or the Christians be satisfied with thee unless thou follow their form of religion. Say: "The Guidance of Allah,-that is the (only) Guidance." Wert thou to follow their desires after the knowledge which hath reached thee, then wouldst thou find neither Protector nor helper against Allah.]]></Verse>
		<Verse VerseID="121"><![CDATA[Those to whom We have sent the Book study it as it should be studied: They are the ones that believe therein: Those who reject faith therein,- the loss is their own.]]></Verse>
		<Verse VerseID="122"><![CDATA[O Children of Israel! call to mind the special favour which I bestowed upon you, and that I preferred you to all others (for My Message).]]></Verse>
		<Verse VerseID="123"><![CDATA[Then guard yourselves against a-Day when one soul shall not avail another, nor shall compensation be accepted from her nor shall intercession profit her nor shall anyone be helped (from outside).]]></Verse>